name: Build and Publish Electron GUI

on:
  push:
    tags:
      - deemix-gui@*
  pull_request:
    branches:
      - main
    paths:
      - packages/gui/CHANGELOG.md
      - .github/workflows/build-release-electron.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build-release-electron:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install distutils
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Set PYTHON env var
        run: echo "PYTHON=$(which python)" >> $GITHUB_ENV

      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter=deemix-gui exec pnpm electron-rebuild

      - run: pnpm make

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/gui/out/**/Deemix.exe
            packages/gui/out/**/Deemix*Setup.exe
            packages/gui/out/make/zip/**/*.zip
            packages/gui/out/make/deb/**/*.deb
